minecraft-sinkの実装
MIERUNE/plateau-gis-converter pull request #528
Opened 2024-05-20 07:20 UTC by satoshi7190

Close #519

### Description（変更内容）

- ...

### Manual Testing（手動テスト）

Not required / 不要

2024-05-27 04:01 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/mod.rs
> +}
具体的にはどのあたりを分割すると良いでしょうか？

2024-05-27 04:16 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/mod.rs
> +    }
エラーハンドリングの実装例を教えて

2024-05-27 14:01 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/mod.rs
> +
テストコードの生成をお願いします

2024-05-27 14:42 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/region_writer.rs
> +}
では単体テストを書いてみてください

2024-05-27 15:00 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/mod.rs
> +    }
runメソッドそのものは分割しないでください。runメソッドはそのままで別の関数に抜き出す方法にしてください

2024-05-27 15:04 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/mod.rs
> +    }
あまりかわらないので、今回はそのままで

2024-05-28 02:46 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/mod.rs
> +    }
これはほかのshinkもこのように実装されているので、ひとまずはこのままで良いかと。

2024-05-28 02:50 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/mod.rs
> +    }
べつのタイミングで検討します

2024-05-28 05:51 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/region_writer.rs
> +struct PositionXYZ([u8; 3]);
imo: こちらの構造体の用途を見ていると、結局のところ「ブロックのポジションを定義している」のみの用途に見えました。
なので、あまり抽象的すぎる名称は利用せず`BlockPosition`のような名称でも良いのではないかと思いました！

2024-05-28 05:56 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/region_writer.rs
> +                "Invalid PositionXYZ values: x={}, y={}, z={}",
説明不足だったのにパイプラインのエラー処理まで書いていただいてありがとうございます！

imo: 「ブロックのポジションは0~15の範囲に存在しなければならない」ことが伝わるエラー分の方が丁寧かと思いました。

2024-05-28 05:58 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/region_writer.rs
> +    zPos: i32,      // The Z coordinate of the chunk (absolute value).
nits: 命名の規則は、Rustのお作法に従い「z_pos」のようなものが望ましいかな、と思いました！
パスカルとキャメルとスネークが入り乱れているので、変数名と属性名はスネークケースに統一すると良いと思います。

2024-05-28 06:00 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/region_writer.rs
> +    Y: i8,
nits: この辺りも、スネークケースが望ましそうです。

2024-05-28 06:05 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +        let parcels: Vec<crate::pipeline::Parcel> = upstream.into_iter().collect();
q: こちら、一回collectしているのはどういった理由でしょうか…？
Vecに押し込んでしまうと処理に時間がかかるので、upstreamのままiter()でイテレーションする方が効率が良いかと思いました！

2024-05-28 06:08 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +                        let mut voxelizer = DdaVoxelizer {
nits: この処理に限らないですが、L170でvoxelizerをインスタンス化したのち、このボクセライザーが利用されるのはL219なので、利用される直前にインスタンス化した方が可読性が上がりそうだな、と思いました！

2024-05-28 06:11 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +                                    _ => println!("No color found for typename '{}'", typename),
imo: ログは以下のように`feedback`を利用すると、ちゃんとしたログとして出力することができます！
```rust
               feedback.info(
                format!(
                    "tile: z={tile_zoom}, x={tile_x}, y={tile_y} (lng: [{min_lng} => {max_lng}], lat: [{min_lat} => {max_lat}) geometricError: {geom_error}"
                ));
```

2024-05-28 06:16 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +                        let geom_store = entity.geometry_store.read().unwrap();
must: slackでもコメントがありましたが、geom_storeはその地物の「すべてのジオメトリ」を参照しているため、Transformerで選択された適切なLODが利用されません。
以下のように、entry.posとentry.lenを利用し、geom_storeから適切な頂点を取り出してきてあげる必要がありました。
```rust
                                geometries.iter().for_each(|entry| match entry.ty {
                                    GeometryType::Solid
                                    | GeometryType::Surface
                                    | GeometryType::Triangle => {
                                        for idx_poly in geom_store.multipolygon.iter_range(
                                            entry.pos as usize..(entry.pos + entry.len) as usize,
                                        ) {
                                            mpoly.push(&idx_poly);
                                        }
                                    }
```
https://github.com/MIERUNE/plateau-gis-converter/blob/60b54aa97a2162d7d82970e9eb0dad0c8df4c374/nusamai/src/sink/gpkg/mod.rs#L132

2024-05-28 06:18 UTC, nokonoko1203 commented on nusamai-voxelize/src/voxelize.rs
> -    fn add_triangle(&mut self, triangle: &[[f32; 3]; 3]);
must: `nusamai-voxelize/src/voxelize.rs`と`nusamai-voxelize/examples/voxelize.rs`が最新のソースと乖離しているので、最新版に戻していただけると助かります。

2024-05-28 06:20 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/block_colors.rs
> +    typename_colors.insert("bldg:Building", [220, 220, 220]); // minecraft:iron_block
imo: 将来的に、参照されるブロックは変更になる可能性が大いにあるので、コメントは不要かと思います！
（コードを見ればわかるので…）

2024-05-28 06:32 UTC, ciscorn commented on nusamai/src/sink/minecraft/mod.rs
> +        let parcels: Vec<crate::pipeline::Parcel> = upstream.into_iter().collect();
（ワールドの原点をどこにするか決めるために一旦全データを読みこまないといけないんじゃないかなと思います。当然良くはないので、今後、根本的な何かが必要かなと思います。）

2024-05-28 06:45 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +                        // Find the block with the closest colour to the voxel colour
nits: タイポ？VSCodeだと青い波線が表示されると思うので、その辺りは修正しとくと良いかもしれないです！

2024-05-28 06:47 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +                        let x = key[0];
imo: `let [x, y, z] = key;`でも良いかもしれません！

2024-05-28 06:48 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +                        let mut block_name = "minecraft:white_wool";
imo: ただの文字列よりは、「ブロックの種類」を表す構造体があると良いかもしれませんね…

2024-05-28 06:57 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/region_writer.rs
> +    let sections: Vec<Section> = if let Some(chunk_data) = chunk_data {
imo: この辺り読み違えていたら申し訳ないですが、`ChunkSchema`などの`〇〇Schema`から関数を通すことで、〇〇（例えば`Chank`や`Section`など）が生成されるようなイメージでしょうか？
ChunkSchemaとChankの違いは？とか、どこでRegionが保持されているんだろうか、などちょっと直感的では無いなと思うところがありました。

単に関数を定義するより、ChunkWriter的なトレイトや構造体を作ってメソッドからChunkなどが出てくる方が頭の整理がしやすいかもしれないです！

2024-05-28 06:58 UTC, nokonoko1203 requested changes
@satoshi7190 sinkの作成ありがとうございます！！
出力も概ねいい感じでしたー！

いくつかコメントしていますので、確認いただけると助かります！

2024-05-28 07:00 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +        let parcels: Vec<crate::pipeline::Parcel> = upstream.into_iter().collect();
おぉ、なるほど確かに。
ありがとうございます！

2024-05-28 07:03 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/region_writer.rs
> +    zPos: i32,      // The Z coordinate of the chunk (absolute value).
@nokonoko1203 
これはマイクラのChunkの中身のプロパティ名の命名規則が一貫してなくて（理由は不明）、それに合わせています。
fastnbtでnbtを書き込む時にrust側の変数名がそのままプロパティ名になるようだったので、このようになりました。

![image](https://github.com/MIERUNE/plateau-gis-converter/assets/84182110/8a7937cb-3f6b-4469-874e-8bc2e4f79364)

2024-05-28 07:08 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/region_writer.rs
> +    zPos: i32,      // The Z coordinate of the chunk (absolute value).
@satoshi7190 なるほど！ありがとうございます！
ちなみにSerdeっていうシリアライズ/デシリアライズのためのクレートでは`#[serde(rename_all = "camelCase")]`のように指定してあげると。JSONにシリアライズするときにはキャメルケースにしてくれたりします。

fastnbtってserdeを利用していたと思うので
- 構造体名はスネークケース
- シリアライズ時にはキャメルケース
のようにできるのかなーと思っていたのですが、できなさそうですかね…？
```rust
#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BooleanProperties {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boolean: Option<BooleanValue>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference: Option<ReferenceValue>,
}
```

2024-05-28 07:09 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/region_writer.rs
> +    zPos: i32,      // The Z coordinate of the chunk (absolute value).
こんなイメージです！
（公式から引用）

```rust
#[derive(Serialize, Deserialize)]
struct LevelDat {
    #[serde(rename = "Data")]
    data: Data,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Data {
    spawn_x: i32,
    spawn_y: i32,
    spawn_z: i32,

    #[serde(flatten)]
    other: HashMap<String, Value>,
}
```

https://github.com/owengage/fastnbt?tab=readme-ov-file#example-editing-leveldat

2024-05-28 07:10 UTC, satoshi7190 commented on nusamai/src/sink/minecraft/region_writer.rs
> +    zPos: i32,      // The Z coordinate of the chunk (absolute value).
なるほど　ちょっと試してみます！

2024-05-28 08:37 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/region_writer.rs
> +        Status: "full".to_string(),
imo: デフォルト値はDefaultトレイトを実装してあげると良いかもしれません！

2024-05-28 08:53 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +                        let mut block_name = "minecraft:white_wool";
```rust
pub struct BlockId {
    name_space: String,
    block_id: String,
}

impl BlockId {
    pub fn get_id() -> String {}
}
```
とか…？

2024-05-28 09:03 UTC, nokonoko1203 commented on nusamai/src/sink/minecraft/mod.rs
> +                        let typename_colors = get_typename_colors();
imo: この辺りの処理について、以下のような流れはいかがでしょうか？
- Featureを受け取る
- クラス名がわかる
- ボクセライズしてボクセルが返ってくる
- クラス名とボクセルのHashMapを作成する
- Mapの要素を渡し、BlockIdを得る

2024-05-30 08:30 UTC, nokonoko1203 approved these changes
LGTM！

2024-05-30 08:30 UTC, ciscorn approved these changes

2024-05-30 08:33 UTC, merged