3dtiles: EXT_texture_webpを利用する
MIERUNE/plateau-gis-converter pull request #604
Opened 2024-07-11 02:35 UTC by satoshi7190

Close #597

### Description（変更内容）

- テクスチャにwebpが含まれている場合、EXT_texture_webpの拡張機能を利用するように変更

### Notes（連絡事項）

- None / なし

2024-07-16 00:52 UTC, nokonoko1203 commented on nusamai/src/sink/cesiumtiles/material.rs
> +        let extension = self
fyi: pathからextentionを取り出すメソッドが存在するため、こんなコードの方が安全に思えました！
（あと、Stringの利用をちょっとだけ減らしました。）
```rust
    let extension = Path::new(self.uri.path())
        .extension()
        .and_then(|ext| ext.to_str())
        .map(|ext| ext.to_lowercase());

    if extension.as_deref() == Some("webp") {
        nusamai_gltf_json::Texture {
            extensions: Some(nusamai_gltf_json::extensions::texture::TextureExtensions {
                ext_texture_webp: Some(
                    nusamai_gltf_json::extensions::texture::EXTTextureWebP {
                        source: image_index as u32,
                    },
                ),
                others: HashMap::new(),
            }),
            source: Some(image_index as u32),
            ..Default::default()
        }
    } else {
        nusamai_gltf_json::Texture {
            source: Some(image_index as u32),
            ..Default::default()
        }
    }
```

2024-07-16 00:53 UTC, nokonoko1203 commented on nusamai/src/sink/cesiumtiles/material.rs
> +                    others: HashMap::new(),
nits: `..Default::default()`で良いかも

2024-07-16 00:55 UTC, nokonoko1203 commented on nusamai/src/sink/cesiumtiles/gltf.rs
> +        texture
nits: material.rsでのロジックと同じようになっていると嬉しいです！

2024-07-16 00:57 UTC, nokonoko1203 commented on nusamai/src/sink/cesiumtiles/gltf.rs
> +    if has_webp_texture(&gltf_textures) {
must: トップレベルのextentionsに`EXT_texture_webp`を定義する必要はないのでは…？
textures以下に定義されていれば問題なく機能すると思っていました。
要確認（動作も含め）でお願いします！

https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_texture_webp/README.md

2024-07-16 01:02 UTC, nokonoko1203 commented on nusamai-gltf/nusamai-gltf-json/src/models/extensions/texture/mod.rs
> +pub struct EXTTextureWebP {
nits: `ExtTextureWebP`

2024-07-16 01:04 UTC, nokonoko1203 requested changes
@satoshi7190 ちょっと気になる点があったのでいくつかコメントしています！！

2024-07-17 06:53 UTC, satoshi7190 commented on nusamai/src/sink/cesiumtiles/gltf.rs
> +    if has_webp_texture(&gltf_textures) {
動作的には問題ないですがm定義しないとコード上で怒られますね
![image](https://github.com/user-attachments/assets/e3235c32-b7ac-4947-b90e-733cd4645e90)

```
# 翻訳
extensionsUsed.glTF Validator(UNDECLARED_EXTENSION) でエクステンションが宣言されていません。
EXT_texture_webp glTF 拡張。

WebP 画像フォーマットを使ってテクスチャを指定するための glTF 拡張。
```

2024-07-17 09:31 UTC, satoshi7190 commented on nusamai/src/sink/cesiumtiles/gltf.rs
> +        texture
@nokonoko1203 
すいません。こちらは拡張子を確認して条件を分岐するようにということでしょうか？

```rust
  if extension == Some("webp".to_string()) {
            vec![
            "EXT_mesh_features".to_string(),
            "EXT_structural_metadata".to_string(),
            "EXT_texture_webp".to_string()
        ];
        } else {
          vec![
            "EXT_mesh_features".to_string(),
            "EXT_structural_metadata".to_string(),
        ];
        }

```

2024-07-17 11:09 UTC, nokonoko1203 commented on nusamai/src/sink/cesiumtiles/gltf.rs
> +        texture
@satoshi7190 違います！このmaterial.rsでの指摘と大体同じように修正するのが良いかなーという意味でした！
```rust
    let extension = Path::new(self.uri.path())
        .extension()
        .and_then(|ext| ext.to_str())
        .map(|ext| ext.to_lowercase());

    if extension.as_deref() == Some("webp") {
        nusamai_gltf_json::Texture {
            extensions: Some(nusamai_gltf_json::extensions::texture::TextureExtensions {
                ext_texture_webp: Some(
                    nusamai_gltf_json::extensions::texture::EXTTextureWebP {
                        source: image_index as u32,
                    },
                ),
                others: HashMap::new(),
            }),
            source: Some(image_index as u32),
            ..Default::default()
        }
    } else {
        nusamai_gltf_json::Texture {
            source: Some(image_index as u32),
            ..Default::default()
        }
    }
```

2024-07-18 02:04 UTC, satoshi7190 commented on nusamai/src/sink/cesiumtiles/gltf.rs
> +        texture
@nokonoko1203 こういうことでしょうか？（関数に切り出さないうようにしました）
```rust
let has_webp = gltf_textures.iter().any(|texture| {
        texture
            .extensions
            .as_ref()
            .and_then(|ext| ext.ext_texture_webp.as_ref())
            .map_or(false, |_| true)
    });

let extensions_used = {
    let mut extensions_used = vec![
        "EXT_mesh_features".to_string(),
        "EXT_structural_metadata".to_string(),
    ];

    // Add "EXT_texture_webp" extension if WebP textures are present
    if has_webp {
        extensions_used.push("EXT_texture_webp".to_string());
    }

    extensions_used
};
```

2024-07-18 02:04 UTC, nokonoko1203 commented on nusamai/src/sink/cesiumtiles/gltf.rs
> +        texture
良さげに見えます！ありがとうございます！

2024-07-18 03:24 UTC, nokonoko1203 approved these changes

2024-07-18 03:25 UTC, nokonoko1203 reviewed
LGTM!

2024-07-18 03:25 UTC, merged