LODレベルを選択できるオプションを追加
MIERUNE/plateau-gis-converter pull request #635
Opened 2024-09-02 06:03 UTC by satoshi7190

Close #571 

### What I did（変更内容）

- 出力時にLODの種類を選択できるようにしました
![image](https://github.com/user-attachments/assets/ab69dc4f-d948-429b-9ebd-b0039fdf3de4)

- 変換時に選択したLODが存在しなかったときはエラーを出すようにしました
![image](https://github.com/user-attachments/assets/cad71fe0-330d-45b6-bd9c-51fa8d66b22f)

### Notes（連絡事項）

None / なし

2024-09-05 05:04 UTC, nokonoko1203 commented on nusamai/src/pipeline/runner.rs
>      let handle = spawn_thread("pipeline-transformer".to_string(), move || {
nits: `main_thread_feedback`とかでも良いかも？

2024-09-05 05:04 UTC, nokonoko1203 commented on nusamai/src/pipeline/runner.rs
> +        let transformer_feedback = feedback.component_span(super::SourceComponent::Transformer);
nits: `child_thread_feedback`とかでも良いかも？

2024-09-05 05:05 UTC, nokonoko1203 commented on nusamai/src/pipeline/runner.rs
> +    mut sink: Box<dyn DataSink>, //NOTE: test
q) `NOTE: test`はどういう意味でしょう？

2024-09-05 05:10 UTC, nokonoko1203 commented on nusamai/src/main.rs
> +    #[arg(short = 't', value_parser = parse_key_val)]
imo) オプションの短縮名が`o`と`t`の2つありますが、どちらもオプションなので役割がわかりづらいなぁと
…
パッと思い浮かばないのですが、せめてコメントは入れておきたくて、「oはsinkのオプション設定であり、出力ファイルフォーマットに関係する」「tはtransformerのオプション設定であり、地物の座標や属性ツリーに関係する」ことが分かると嬉しいです！

2024-09-05 05:18 UTC, nokonoko1203 commented on nusamai/src/transformer/transform/lods.rs
> +            LodFilterMode::Lod0 => lods.has_lod(0).then_some(0),
q) テクスチャ付き最大LODは未実装？

2024-09-05 05:19 UTC, nokonoko1203 commented on nusamai/src/transformer/transform/lods.rs
> +#[derive(Default, Clone, Copy, Debug)]
nits: もう不要であればDebugは除去しても良いかも？

2024-09-05 05:29 UTC, nokonoko1203 commented on nusamai/src/main.rs
> +    let mut had_error = false;
imo) had_errorをtrueにしにいく箇所が複数あり、どこか一つでもerrorになっていると処理が停止してしまうのであれば、即座に`return ExitCode::FAILURE;`をしてしまっても良いのではと思いました！

2024-09-05 05:32 UTC, nokonoko1203 commented on nusamai/src/main.rs
> +        let transformer_registry = sink_provider.available_transformer();
imo) 元々スコープを切っていた理由がわからないですが、スコープで囲わずに、以下のようにしても良いのでは、と思いました！
```rust
    let sink_provider: &dyn DataSinkProvider = args.sink.create_sink();
    let mut sink_params = sink_provider.parameters();
    if let Err(err) = sink_params.update_values_with_str(&args.sinkopt) {
        log::error!("Error parsing sink options: {:?}", err);
        return ExitCode::FAILURE;
    };
    if let Err(err) = sink_params.validate() {
        log::error!("Error validating sink parameters: {:?}", err);
        return ExitCode::FAILURE;
    }

    // If the directory for the output path does not exist, create it
    if let Some(output_parent_dir) = PathBuf::from(&args.output).parent() {
        if !output_parent_dir.exists() {
            if std::fs::create_dir_all(output_parent_dir).is_err() {
                log::error!("Failed to create output directory: {:?}", output_parent_dir);
                return ExitCode::FAILURE;
            };
            log::info!("Created output directory: {:?}", output_parent_dir);
        }
    }

    let sink = sink_provider.create(&sink_params);
    let transformer_registry = sink_provider.available_transformer();
```

2024-09-05 05:53 UTC, nokonoko1203 commented on nusamai/src/transformer/setting.rs
> +                            "max_lod" => {
imo) うーん…この実装だと「lodの指定」以外のSelectionを追加したくなった時に、いじる必要が出てくると思います。
Selectionであることと、lodの指定は異なる概念だと思うので、分離したいです。
（issue化でも良いですが…）

2024-09-05 05:53 UTC, nokonoko1203 commented on nusamai/src/transformer/setting.rs
> +                    if config.key == "use_texture" {
imo) `ParameterType::Selection`と同様です。

2024-09-05 05:58 UTC, nokonoko1203 commented on nusamai/src/sink/cesiumtiles/mod.rs
>      fn available_transformer(&self) -> TransformerRegistry {
imo) この際、以下のようなイメージの方がわかりやすいかもしれないですね。
- available_transformer → transformer_options
- parameters → sink_options

2024-09-05 06:01 UTC, nokonoko1203 commented on nusamai/src/sink/cesiumtiles/mod.rs
>      fn available_transformer(&self) -> TransformerRegistry {
imo) そもそも、というところで
- `sink/option.rs`みたいなものを作って各sinkで共有した方が良いのではないだろうか
- `transformer/option.rs`みたいなものを作って各sinkで共有した方が良いのではないだろうか
と思いました！

2024-09-05 06:03 UTC, nokonoko1203 commented on nusamai/src/transformer/setting.rs
> +    pub fn new_lod_selections(selected_value: &str) -> Self {
imo) `Selection`は「セレクター」的な概念をモデル化したものであって、「LODをセレクトする」という個別具体の操作を`Selection`に実装するべきではないと感じました！

2024-09-05 06:04 UTC, nokonoko1203 requested changes
@satoshi7190 UIに辿り着いていませんが、コメントしています！
一部、mustの対応があるかもしれません。

2024-09-05 06:10 UTC, satoshi7190 commented on nusamai/src/pipeline/runner.rs
> +    mut sink: Box<dyn DataSink>, //NOTE: test
これは消し忘れなので消しておきます

2024-09-09 03:04 UTC, satoshi7190 commented on nusamai/src/transformer/transform/lods.rs
> +            LodFilterMode::Lod0 => lods.has_lod(0).then_some(0),
テクスチャ付き最大LODの対応は別で対応します。このPRは https://github.com/MIERUNE/plateau-gis-converter/issues/571 の対応のみとします

2024-09-10 07:19 UTC, satoshi7190 commented on nusamai/src/transformer/setting.rs
> +                            "max_lod" => {
これは別イシューで対応します

2024-09-10 07:20 UTC, satoshi7190 commented on nusamai/src/sink/cesiumtiles/mod.rs
>      fn available_transformer(&self) -> TransformerRegistry {
`sink/option.rs`と`transformer/option.rs`に共通して使われるオプションを作成する関数を定義しました。

2024-09-12 07:20 UTC, nokonoko1203 commented on nusamai/src/transformer/transform/lods.rs
> +            LodFilterMode::Lod0 => lods.has_lod(0).then_some(0),
@satoshi7190 issue化が必要なものは忘れちゃうので随時追加お願いしたいです！

2024-09-12 07:20 UTC, nokonoko1203 commented on nusamai/src/transformer/setting.rs
> +                            "max_lod" => {
@satoshi7190 こちらもissue化お願いします！
すでにあったらすみません！

2024-09-12 07:28 UTC, nokonoko1203 approved these changes
@satoshi7190 色々別のissueがあるかと思いますが！このPRはlgtmです！

2024-09-12 07:28 UTC, merged